brew "go"
brew "uv"
brew "git"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "gh"
brew "fzf"
brew "jq"
brew "starship"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "claude-code"
cask "wezterm"
cask "font-jetbrains-mono-nerd-font"
cask "raycast"
